language: go

go:
  - 1.3
  - 1.4
  - tip

before_install:
  - go get github.com/golang/lint/golint
  - go get golang.org/x/tools/cmd/vet
  - go get github.com/fzipp/gocyclo
  - go get github.com/axw/gocov/gocov
  - go get github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi

install:
  - go build

script:
  - gofmt -l -s .
  - go vet ./...
  - go get -t
  - $HOME/gopath/bin/goveralls -service=travis-ci -repotoken=$COVERALLS -v

after_script:
  - golint ./...
  - gocyclo -over 15 . || true
  - |
    if [[ "$TRAVIS_PULL_REQUEST" == "false" ]] && [[ "$TRAVIS_BRANCH" == "master" ]]; then
      go list ./... | xargs -n 1 -I{} curl http://godoc.org/-/refresh -d path={}
    fi